# Generated by Django 5.2.8 on 2025-11-29 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Oggetto')),
                ('message', models.TextField(verbose_name='Messaggio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data invio')),
                ('is_read', models.BooleanField(default=False, verbose_name='Letto')),
            ],
            options={
                'verbose_name': 'Messaggio',
                'verbose_name_plural': 'Messaggi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome del progetto (max 100 caratteri)', max_length=100, verbose_name='Titolo')),
                ('slug', models.SlugField(blank=True, help_text='Generato automaticamente dal titolo', unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(help_text='Descrizione breve del progetto (max 50 parole consigliato)', verbose_name='Descrizione breve')),
                ('long_description', models.TextField(blank=True, help_text='Descrizione estesa per la pagina dettaglio (case study)', verbose_name='Descrizione dettagliata')),
                ('challenge', models.TextField(blank=True, help_text='Quale problema doveva risolvere il progetto?', verbose_name='La sfida')),
                ('solution', models.TextField(blank=True, help_text='Come hai risolto il problema?', verbose_name='La soluzione')),
                ('results', models.TextField(blank=True, help_text='Quali risultati ha ottenuto il progetto?', verbose_name='I risultati')),
                ('image_thumbnail', models.ImageField(help_text='Immagine principale del progetto (ratio 16:9 consigliato)', upload_to='projects/thumbnails/', verbose_name='Immagine thumbnail')),
                ('image_hero', models.ImageField(blank=True, help_text='Immagine grande per la pagina dettaglio', null=True, upload_to='projects/heroes/', verbose_name='Immagine hero')),
                ('gallery', models.JSONField(blank=True, default=list, help_text='Lista di URL immagini aggiuntive (JSON array)', verbose_name='Galleria immagini')),
                ('tech_stack', models.JSONField(default=list, help_text='Lista tecnologie usate (es: ["Python", "Django", "PostgreSQL"])', verbose_name='Tech Stack')),
                ('external_url', models.URLField(blank=True, help_text='Link al sito live del progetto', verbose_name='URL Progetto')),
                ('github_url', models.URLField(blank=True, help_text='Link al repository GitHub', verbose_name='URL GitHub')),
                ('featured', models.BooleanField(default=False, help_text='Mostra questo progetto in evidenza nella homepage', verbose_name='In evidenza')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Fullstack'), ('design', 'Design'), ('mobile', 'Mobile')], default='fullstack', max_length=20, verbose_name='Categoria')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione (numero più basso = prima posizione)', verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo aggiornamento')),
                ('is_visible', models.BooleanField(default=True, help_text='Rendi il progetto visibile nel portfolio', verbose_name='Visibile')),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Luigi Portfolio', max_length=100, verbose_name='Nome sito')),
                ('tagline', models.CharField(default='Web Developer', max_length=200, verbose_name='Tagline')),
                ('hero_title', models.CharField(default='Creo esperienze digitali', max_length=200, verbose_name='Titolo Hero')),
                ('hero_subtitle', models.TextField(default='Web Developer specializzato nella creazione di siti web moderni, performanti e user-friendly.', verbose_name='Sottotitolo Hero')),
                ('about_text', models.TextField(blank=True, verbose_name='Testo "Chi sono"')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Foto profilo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Località')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='CV PDF')),
                ('projects_completed', models.PositiveIntegerField(default=15, verbose_name='Progetti completati')),
                ('sites_live', models.PositiveIntegerField(default=10, verbose_name='Siti online')),
                ('years_experience', models.PositiveIntegerField(default=3, verbose_name='Anni esperienza')),
                ('happy_clients', models.PositiveIntegerField(default=12, verbose_name='Clienti soddisfatti')),
            ],
            options={
                'verbose_name': 'Impostazioni Sito',
                'verbose_name_plural': 'Impostazioni Sito',
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titolo')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='Tecnologie usate in questo periodo', verbose_name='Tech Stack')),
                ('year', models.CharField(help_text='Es: "2020", "2019-2021", "Presente"', max_length=20, verbose_name='Anno/Periodo')),
                ('icon', models.CharField(blank=True, help_text='Classe CSS icona', max_length=50, verbose_name='Icona')),
                ('color', models.CharField(default='#00d9ff', help_text='Colore del punto timeline (hex)', max_length=20, verbose_name='Colore')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visibile')),
            ],
            options={
                'verbose_name': 'Evento Timeline',
                'verbose_name_plural': 'Eventi Timeline',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome skill')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('tools', 'Tools & DevOps'), ('soft', 'Soft Skills')], max_length=20, verbose_name='Categoria')),
                ('icon', models.CharField(blank=True, help_text="Classe CSS per l'icona (es: fab fa-python)", max_length=50, verbose_name='Classe icona')),
                ('years_experience', models.PositiveSmallIntegerField(default=1, verbose_name='Anni esperienza')),
                ('proficiency', models.PositiveSmallIntegerField(default=80, help_text='Livello di competenza da 0 a 100', verbose_name='Livello (%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visibile')),
                ('related_projects', models.ManyToManyField(blank=True, related_name='skills', to='portfolio.project', verbose_name='Progetti correlati')),
            ],
            options={
                'verbose_name': 'Competenza',
                'verbose_name_plural': 'Competenze',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('role', models.CharField(max_length=100, verbose_name='Ruolo/Azienda')),
                ('quote', models.TextField(help_text='La testimonianza del cliente', verbose_name='Citazione')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto profilo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visibile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.project', verbose_name='Progetto correlato')),
            ],
            options={
                'verbose_name': 'Testimonianza',
                'verbose_name_plural': 'Testimonianze',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
